### ISSUE TITLE
Update Downtime Matrix report to use bootstrap

### ISSUE THREAD

**Issue by JoePlant** [Ampla/ProjectAnalysis#21]
Update the Downtime Relationship report to use bootstrap and optimise for large projects

**Comment by JoePlant** [comment]
Completed

**Comment by Skaaal** [comment]
The downtime matrix output is very helpful to share with customers and review the configuration with them.  As the number of equipment, equipment types and causes grows it is really a must-have tool. Thanks for sharing!

**Comment by JoePlant** [comment]
Pascal, glad to know that you are using it.  Joseph
