### ISSUE TITLE
Excel Security report

### ISSUE THREAD

**Issue by JoePlant** [Ampla/ProjectAnalysis#30]
Create an Excel security report from the Authstore data
Include:
- Security Matrix of operations per role
- Role Summary - number of locations with the role and list of users with role
- User summary - list of roles and number of locations they have permissions
- Location summary - list of roles and users for each location in the project
- Tables of data for use in pivot tables.

**Comment by JoePlant** [comment]
Code checked in earlier today.

**Comment by alexmg** [comment]
Nice one.
